### ISSUE TITLE
Template error while templating string

### ISSUE THREAD

**Issue by eegilbert** [GROG/ansible-role-authorized-key#5]
ASK [GROG.authorized-key : Manage authorized keys] *********************************************************************************************************************************************************************************************
task path: /private/etc/ansible/roles/GROG.authorized-key/tasks/main.yml:3
fatal: [10.82.136.9]: FAILED! => {
    "failed": true, 
    "msg": "{{ authorized_key_list + authorized_key_list_host + authorized_key_list_group }}: [{u'authorized_keys': [{u'key': u\"{{ lookup('file', 'files/user.keys) }}\"}], u'name': u'user'}]: template error while templating string: unexpected char u\"'\" at 18. String: {{ lookup('file', 'files/user.keys) }}"
}
fatal: [10.104.136.14]: FAILED! => {
    "failed": true, 
    "msg": "{{ authorized_key_list + authorized_key_list_host + authorized_key_list_group }}: [{u'authorized_keys': [{u'key': u\"{{ lookup('file', 'files/user.keys) }}\"}], u'name': u'user'}]: template error while templating string: unexpected char u\"'\" at 18. String: {{ lookup('file', 'files/user.keys) }}"
}
fatal: [10.3.8.5]: FAILED! => {
    "failed": true, 
    "msg": "{{ authorized_key_list + authorized_key_list_host + authorized_key_list_group }}: [{u'authorized_keys': [{u'key': u\"{{ lookup('file', 'files/user.keys) }}\"}], u'name': u'user'}]: template error while templating string: unexpected char u\"'\" at 18. String: {{ lookup('file', 'files/user.keys) }}"
}

ssh-keys.yaml:

    ---
    - hosts: azure
      roles:
        - { role: GROG.authorized-key, become: yes }

servers.yaml

    authorized_key_list_group:
      - name: egilb1
        authorized_keys:
          - key: "{{ lookup('file', 'files/egilb1.keys) }}"

files/user.keys is in the dir I'm running the playbook from, so the path is relative.

**Comment by groggemans** [comment]
@eegilbert Your missing a quote at the end of the key path;
```
  - key: "{{ lookup('file', 'files/egilb1.keys') }}"
                                              ^
                                              ^
```

**Comment by eegilbert** [comment]
Oh! indeed, thank you! 👍

**Comment by groggemans** [comment]
NP!
