### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPSConnection'

### ISSUE THREAD

**Issue by thalunil** [GROG/ansible-role-authorized-key#9]
On a fresh opensuse 15.1 installation i get an AttributeError.
Another opensuse 15.1 installation works flawlessly.
Any clue what kind of dependency is missing?

thanks!
------------------
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/tmp/ansible_authorized_key_payload_4oX_0b/__main__.py", line 230, in <module>
  File "/tmp/ansible_authorized_key_payload_4oX_0b/ansible_authorized_key_payload.zip/ansible/module_utils/urls.py", line 402, in <module>
AttributeError: 'module' object has no attribute 'HTTPSConnection'

failed: [test] (item=[{'name': 'acb'}, {'key': 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFS3XxUR92/mvUnjDgYBW7tUl0sp6uT28WG9CzIIPQXP 20190710 - harkonnen - kallisti'}]) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": [
        {
            "name": "acb"
        },
        {
            "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFS3XxUR92/mvUnjDgYBW7tUl0sp6uT28WG9CzIIPQXP 20190710 - harkonnen - kallisti"
        }
    ],
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_authorized_key_payload_4oX_0b/__main__.py\", line 230, in <module>\n  File \"/tmp/ansible_authorized_key_payload_4oX_0b/ansible_authorized_key_payload.zip/ansible/module_utils/urls.py\", line 402, in <module>\nAttributeError: 'module' object has no attribute 'HTTPSConnection'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by groggemans** [comment]
Hi Thal

You're probably missing one of the ansible python dependencies.
I'd recommend to install the latest version using pip (see also https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-pip)

Kind Regards
Gertjan

**Comment by agaffney** [comment]
https://github.com/ansible/ansible/pull/60049

**Comment by groggemans** [comment]
@agaffney Thank you for the reference!

@thalunil I'm going to close this issue, as the problem seems to be found and is outside of my control. Please don't hesitate to open a new issue if you encounter any other issues in the future!
